version: '3.7'

services:
          keycloak:
                image: quay.io/keycloak/keycloak:${KEYCLOAK_IMAGE_TAG:-22.0}
                container_name: keycloak
                restart: always
                init: true
                entrypoint: /opt/keycloak/sbin/entrypoint-wrapper.sh
                environment:
                        -  KEYCLOAK_ADMIN=admin
                        -  KEYCLOAK_ADMIN_PASSWORD=admin
                        -  KEYCLOAK_DEV_MODE=true
                        -  KEYCLOAK_STARTUP_IMPORT=true
                        -  KEYCLOAK_BACKUP_RESTORE=false
                        -  KEYCLOAK_BACKUP_ON_SIGTERM=true
                ports:
                        - "8080:8080"
                volumes:
                        - ./modules/system/src/main/sh/bin:/opt/keycloak/sbin
                        - ./modules/system/src/main/groovy:/opt/keycloak/sbin/groovy
                        - ./lib/groovy:/opt/groovy
                        - ./modules/themes:/opt/keycloak/themes
                        - ./data/import:/opt/keycloak/data/import
                        - ./data/backup:/opt/keycloak/backup
                        - keycloak-data:/opt/keycloak/data
volumes:
  keycloak-data: