version: '3.7'

services:
          keycloak:
                build:
                  context: .
                container_name: keycloak
                restart: always
                stop_grace_period: 1m  # Avoids interrupting the backup script
                environment:
                        -  KC_HOSTNAME=localhost
                        -  KEYCLOAK_ADMIN=admin
                        -  KEYCLOAK_ADMIN_PASSWORD=admin
                        -  KEYCLOAK_DEV_MODE=true
                        -  KEYCLOAK_BACKUP_ON_SIGTERM=true
                        -  KEYCLOAK_STARTUP_IMPORT=true
                ports:
                        - "8080:8080"
                volumes:
                        - ./dev-data/init/realm:/opt/keycloak/data/import
                        - ./dev-data/backup:/opt/keycloak/backup
                        - ./modules/themes:/opt/keycloak/themes
                        - keycloak-data:/opt/keycloak/data
volumes:
  keycloak-data: